# Generated by Django 3.0.8 on 2020-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(default=0)),
                ('image', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('labels', models.CharField(blank=True, choices=[('offer', 'offer'), ('limited', 'limited')], max_length=100)),
                ('special_offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=100)),
                ('upper_part', models.CharField(max_length=300)),
                ('lower_part', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
