# Generated by Django 3.0.8 on 2020-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200811_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('products', models.ImageField(upload_to='media')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('action', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
