# Generated by Django 3.0.8 on 2020-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='price',
            field=models.FloatField(),
        ),
    ]
