# Generated by Django 3.0.8 on 2020-08-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200813_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='products',
            new_name='place',
        ),
    ]
