# Generated by Django 3.0.8 on 2020-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200813_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='place',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
