# Generated by Django 3.0.8 on 2020-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200813_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='sno',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='action',
            field=models.BooleanField(default=True),
        ),
    ]
