# Generated by Django 3.0.8 on 2020-08-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_checkout_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='productName',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
