# Generated by Django 3.0.8 on 2020-08-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200813_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='placeName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='place',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
