# Generated by Django 3.0.8 on 2020-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200813_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
