# Generated by Django 3.0.8 on 2020-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200813_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
