# Generated by Django 3.0.8 on 2020-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_checkout_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
