# Generated by Django 3.0.8 on 2020-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_checkout_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
